#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems. The assignment is due by 5pm on Friday the 17th of April.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [1]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [55]:
def checkSymmetric(a):
    n=len(a)
    #print(n)
    for i in range(0,n):
        for j in range(i+1,n):
            #print(i,j,a[i,j],a[j,i])
            if(not a[i,j]==a[j,i]):
                return False
                
    return True

Test your function on the two matrices below

In [56]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [57]:
#print(A)
checkSymmetric(A)

False

In [58]:
checkSymmetric(SymMatrix)

True

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library.

In [109]:
def matrixTranspose(a):
    n=len(a)
    out = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            out[j,i]=a[i,j]
    #print(out)
    return out

def matrixEquals(a,b):
    if (not len(a)==len(b)):
        return False
    if (not len(a[0])==len(b[0])):
        return False
    for i in range(len(a)):
        for j in range(len(a[0])):
            if(not a[i,j]==b[i,j]):
                return False
    return True

Check your code by transposing the below random matrix and checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [110]:
A = np.random.rand(6,6)
At = matrixTranspose(A)
print("A:",A)
print("A^T:",At)
print("A==A^T?",matrixEquals(A,At))
print("(A^T)^T-A==0?",matrixEquals(matrixTranspose(At)-A,np.zeros((len(A),len(A)))))


A: [[0.57414197 0.84593178 0.92336336 0.00519456 0.767278   0.28015965]
 [0.99329579 0.38520551 0.94328847 0.41880207 0.7556145  0.16579487]
 [0.46534161 0.85659718 0.46609367 0.0107149  0.12755114 0.86599307]
 [0.34072661 0.04492773 0.52860744 0.05078238 0.96692925 0.98209437]
 [0.77699574 0.22277343 0.3232645  0.03034457 0.12072181 0.98024123]
 [0.59934991 0.78302378 0.22677214 0.88009732 0.48856162 0.09372545]]
A^T: [[0.57414197 0.99329579 0.46534161 0.34072661 0.77699574 0.59934991]
 [0.84593178 0.38520551 0.85659718 0.04492773 0.22277343 0.78302378]
 [0.92336336 0.94328847 0.46609367 0.52860744 0.3232645  0.22677214]
 [0.00519456 0.41880207 0.0107149  0.05078238 0.03034457 0.88009732]
 [0.767278   0.7556145  0.12755114 0.96692925 0.12072181 0.48856162]
 [0.28015965 0.16579487 0.86599307 0.98209437 0.98024123 0.09372545]]
A==A^T? False
(A^T)^T-A==0? True


## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [120]:
def matrixMax(a):
    
    maxIndex = (0,0)
    maxValue = a[maxIndex]
    #print(maxValue)
    for i in range(len(a)):
        for j in range(len(a[0])):
            if(a[i,j]>maxValue):
                maxValue = a[i,j]
                maxIndex = (i,j)
    return maxValue

Check your result by comparing to `np.max(A)` for the below random matrix

In [121]:
A = np.random.rand(4,5)
#print(A[0,0])
matrixMax(A)

0.969385398922196

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()`.

In [126]:
def L1Norm(a):
    maxValue = 0
    maxbool=True
    for j in range(len(a[0])):
        currentSum = 0
        for i in range(len(a)):
            currentSum +=np.abs(a[i,j])
        if(maxbool):
            maxbool=False
            maxValue=currentSum
        else:
            if currentSum>maxValue:
                maxValue = currentSum
    return maxValue

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [133]:
A = np.random.rand(3,4)
print("My value for the L^1-norm:",L1Norm(A))
print("NumPy's L^1-norm:",la.norm(A,1))

My value for the L^1-norm: 1.9512013675560467
NumPy's L^1-norm: 1.9512013675560467


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [134]:
def LInfNorm(a):
    maxValue = 0
    maxbool=True
    for i in range(len(a)):
        currentSum = 0
        for j in range(len(a[0])):
            currentSum +=np.abs(a[i,j])
        if(maxbool):
            maxbool=False
            maxValue=currentSum
        else:
            if currentSum>maxValue:
                maxValue = currentSum
    return maxValue

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [136]:
A = np.random.rand(3,4)
print("My value for the L^inf-norm:",LInfNorm(A))
print("NumPy's L^inf-norm:",la.norm(A,np.inf))

My value for the L^inf-norm: 2.2201890190458937
NumPy's L^inf-norm: 2.2201890190458937


# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [46]:
A1 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A2 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A2$ and $A3$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{2,3\}$.

Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [10]:
# Answer here
#

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [50]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [52]:
A = np.array([[1.935052353404, 0.887037260957, 1.534235483277, 1.370691224125],
       [0.887037260957, 0.81275989158 , 0.610238622918, 0.999150521052],
       [1.534235483277, 0.610238622918, 1.562260333538, 1.007843062517],
       [1.370691224125, 0.999150521052, 1.007843062517, 1.813258814483]])

In [53]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        p = np.dot(A,x)
        lamprev = lam
        lam = np.max(p)
        x = p/lam
        
    x = x/la.norm(x)
    return (lam,x)

Check your answers against Numpy's results from `la.eig(A)`